language: node_js

node_js:
  - stable

cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  # - psql -c "CREATE USER postgres WITH PASSWORD 'Kp15712Kp';" -U postgres
  - npm run create

env:
  global:
    # - DATABASE_URL=postgresql://postgres@localhost/test_db
    - SECRETE_KEY=secrete
    - DATABASE=test_db

script:
  - npm run test

after_success: npm run coverage
